image: macos  # образ для сборки

stack: node 15  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  - yarn install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

test_script:
  - yarn lint && yarn test  # скрипт тестирования
